# Ruff 配置文件
# 更多配置选项请参考: https://docs.astral.sh/ruff/configuration/

line-length = 88
target-version = "py311"

[lint]
# 启用推荐的规则集
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "PTH", # flake8-use-pathlib
    "ERA", # eradicate
    "PL",  # pylint
    "TRY", # tryceratops
    "RUF", # ruff-specific rules
]
ignore = [
    "E501",   # line too long, handled by black
    "B008",   # do not perform function calls in argument defaults
    "C901",   # too complex
    "W191",   # indentation contains tabs
    "PLR0913", # too many arguments
    "PLR0915", # too many statements
    "PLR2004", # magic value used in comparison
    "PLC0415", # import should be at top of file
    "TRY003",  # avoid specifying long messages outside the exception class
    "TRY300",  # consider moving statement to else block
    "TRY301",  # abstract raise to an inner function
    "RUF001",  # ambiguous unicode character (fullwidth colon)
    "RUF002",  # ambiguous unicode character (fullwidth colon)
    "RUF003",  # allow ambiguous comma (fullwidth comma)
]

[lint.per-file-ignores]
"tests/**/*" = ["PLR2004", "S101", "TID252"]
"__init__.py" = ["F401"]

[lint.isort]
known-first-party = ["template-python"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
